# PSOStats Client Config
# Commented values are default settings

# Console UI frames per second, must be between 1 and 30
# uiFps: 5

#serverBaseUrl: https://psostats.com
#autoUpload: true

# Add your credentials here
user: ''
password: ''
