# PSOStats Client Config
# Commented values are default settings

# Console UI frames per second, must be between 1 and 30
# uiFps: 5
serverBaseUrl: http://ec2-18-221-32-14.us-east-2.compute.amazonaws.com