# PSOStats Client Config
# Commented values are default settings

# Console UI frames per second, must be between 1 and 30
# uiFps: 5

#serverBaseUrl: https://psostats.com

# Add your credentials here
user: 'phelix'
password: 'Pb7*6uzfW&VJ!v'